### ISSUE TITLE
mysql_ outdated in PHP 7

### ISSUE THREAD

**Issue by BhiQ** [ErisDS/Migrate#7] opened 2017-11-08 15:30 UTC
mysql_ has been replaced by mysqli_

**Comment by codepotato** [comment] 2017-11-08 15:35
Checkout my pull-request here for the PHP7 version: https://github.com/ErisDS/Migrate/pull/6

**Comment by codepotato** [comment] 2019-02-05 14:52
Duplicate of #6 

Now merged.

**Closed by codepotato** 2019-02-05 14:52 UTC
